site_name: Swiss Cycling Vertical Challenge
site_url: https://swisscycling-vertical.arthurgassner.ch/
theme:
  name: material
  icon:
    logo: material/bike
  palette:
    scheme: slate  # Options: default, slate, or custom
    primary: red  # Primary color
    accent: white     # Accent color
plugins: [] # disable search
nav:
  - Home: index.md  
  - Challenge Overview: challenge_overview.md  
  - Challenge Rules: rules.md
  - Leaderboard: leaderboard.md    
  - Submit A Ride: submit_a_ride.md
  - About: about.md    
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra_css:
  - https://unpkg.com/leaflet/dist/leaflet.css
extra_javascript:
  - https://unpkg.com/leaflet/dist/leaflet.js
  - https://cdn.jsdelivr.net/npm/ag-grid-community/dist/ag-grid-community.min.js
  - https://unpkg.com/leaflet-omnivore@0.3.4/leaflet-omnivore.min.js